import Head from 'next/head'
import { ApolloClient, InMemoryCache } from "@apollo/client";
import {Jobs} from '../query'
import Hero from '../components/Hero'
import Jobboard from '../components/Jobboard';

export default function Home({jobs}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Jobboard jobs={jobs} />
       
    </div>
  )
}

export async function getServerSideProps() {
  const client = new ApolloClient({
    uri: "https://api.graphql.jobs/",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: Jobs,
  });

  return {
    props: {
      jobs: data.jobs
    }
  }
}
